### ISSUE TITLE
Uncaught Error: Call to a member function create() on null in  

### ISSUE THREAD

**Issue by matinict** [baddwin/magento2-ongkir#1]
use Magento\Framework\HTTP\ZendClientFactory; 

Uncaught Error: Call to a member function create() on null in  app/code/Amzone/Ongkir/Model/Query/Api.php:23

**Comment by baddwin** [comment]
Please clear your cache first, and then run `php bin/magento setup:di:compile`

**Comment by kipotlea** [comment]
@matinict , are you solve your issue above?

**Comment by kipotlea** [comment]
@matinict . 
the root causes of the problem are because of wrong writing in Api.php. 
try to change  `__contstruct` to `__construct`

**Comment by baddwin** [comment]
> @matinict .
> the root causes of the problem are because of wrong writing in Api.php.
> try to change `__contstruct` to `__construct`

well done, glad to know that you've discovered the root of issue @kipotlea :+1: 

please submit pull request for it to close the issue, thanks
